### ISSUE TITLE
copy - `std::convert::From<fs_extra::error::Error>` is not implemented for `std::io::Error`

### ISSUE THREAD

**Issue by rofrol** [webdesus/fs_extra#12]
I am using standard example from documentation.

```
dir::copy(&src, &dst, &dir_options)?;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<fs_extra::error::Error>` is not implemented for `std::io::Error`
```
Same for `file::copy`.

**Comment by webdesus** [comment]
Documentation by example does not contain a full work solution. It only shows how it's maybe use. Rust has the symbol `?` which used for more powerful unwrap of object. Read [this](https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator)
Full work example you can find on below of [main page](https://github.com/webdesus/fs_extra#examples) 

Also you can read [tests](https://github.com/webdesus/fs_extra/tree/master/tests). 

If you will bring a more of code, i can help better :wink:

**Comment by rofrol** [comment]
Can you point me to full working example using `dir::copy` and `file::copy` and using `?` operator?

**Comment by webdesus** [comment]
```rust

use std::path::Path;

extern crate fs_extra;
use fs_extra::*;

fn test_copy() -> Result<(), error::Error> {
    let file_in = Path::new("./test_file.txt");
    let file_out = Path::new("./test_out.txt");
    file::write_all(&file_in, "content1")?;
    let options = file::CopyOptions::new();
    file::copy(&file_in, &file_out, &options)?;
    Ok(())
}
fn main() {
    match test_copy() {
        Ok(_) => println!("File was created!"),
        Err(err) => println!("{:?}", err),
    }
}
```

**Comment by webdesus** [comment]
operator `?` it's just a sugar. Without `?`, was like

```rust
    let t = match file::copy(&file_in, &file_out, &options) {
        Ok(v) => v,
        Err(err) => return Err(err),
    };

```

**Comment by webdesus** [comment]
You are have any question?

**Comment by rofrol** [comment]
Thanks

**Comment by rofrol** [comment]
My problem was with error conversion. This works inside main:

```rust
use std::path::Path;

extern crate fs_extra;
use fs_extra::*;

fn main() -> Result<(), Box<std::error::Error>> {
    let file_in = Path::new("./test_file.txt");
    let file_out = Path::new("./test_out.txt");
    file::write_all(&file_in, "content1")?;
    let options = file::CopyOptions::new();
    file::copy(&file_in, &file_out, &options)?;
    Ok(())
}
```
