### ISSUE TITLE
Weird(?) behavior when copying whole directories with dir::copy()

### ISSUE THREAD

**Issue by rask** [webdesus/fs_extra#13]
Inside `/my/source/.git` there is a non-bare git repo with objects, history, etc... Then I want to copy the contents of that directory to a whole other directory at `/my/dest/.git`, which is empty.

```rust
let source = PathBuf::from("/my/source/.git");
let dest = PathBuf::from("/my/dest/.git");

fs_extra::dir::create(&dest, true); // create with erase

let mut copts = fs_extra::dir::CopyOptions::new();
copts.overwrite = true;
copts.copy_inside = true;

let _ = fs_extra::dir::copy(&source, &dest, &copts);
```

After this I would expect to see the following inside `/my/dest/.git`:

```text
/
    my/
        dest/
            .git/
                refs/
                objects/
                ...
```

But instead I see (note nested `.git` inside `.git`)

```text
/
    my/
        dest/
            .git/
                .git/
                    refs/
                    objects/
                    ...
```

This looks like the dest path should be the _parent_ directory to where I want to copy the first directory? Documentation states:

> Copies the directory contents from one place to another using recursive method.

I would assume this means that the _contents_ from source directory become the _contents_ of destination directory, while the directory itself is not copied anywhere?

I'm using fs_extra 1.1.0 and latest stable Rust.

**Comment by rask** [comment]
Okay something funky was just going on, and now it worked as I expected. The `create` method might've broken down somehow as I was still seeing some old files around the destination and source when I ran some testing, will get back to you in case the create with erase does not work as expected. Sorry for the hassle.

**Comment by webdesus** [comment]
> Sorry for the hassle.

Don't worry about that😀 I glad to hear that, you got the expected work. I write many tests cases, we might using their like examples. If we found something wrong, let me know about it😉

**Comment by Weasy666** [comment]
@rask @webdesus I'm still getting that behaviour.

```rust
// output_folder is "static/logos"
fn copy_logos<P: AsRef<Path>>(output_folder: P)  -> Result<(), Box<dyn std::error::Error>> {
    if !output_folder.as_ref().is_dir() {
        std::fs::create_dir_all(output_folder.as_ref())?;
    }

    fs_extra::dir::copy("frontend/vendor/logos", output_folder, &CopyOptions::new())?;

    Ok(())
}
```

With `output_folder = "static/logos"` the files are copied into `static/logos/logos`.

**Comment by webdesus** [comment]
Hi @Weasy666. I checked loggic, all functional work correct. If destenation folder exist, we copy input folder inside output... Like `cp -r` command work. Same behavior. More details you can find here #5

**Comment by Weasy666** [comment]
Hm...but there is no difference in behavior when i change `options.copy_inside` to `false`. Shouldn't it, with one of the options, copy the source folders content into the target folders content?

**Comment by webdesus** [comment]
Option `copy_inside` give different behavior only if destenation folder not exist. Like `cp -r` command work. Maybe you should looking another copy option `options.content_only`. Unfortunately this option not published right now and you should import project by github href `fs_extra = { git = "https://github.com/webdesus/fs_extra", branch = "master" }`. Read more details #11

**Comment by Weasy666** [comment]
That works like charm! Thank you!

**Comment by SirWindfield** [comment]
Would it be possible to publish a new version with `content_only` included? Defining the dependency using the `git` syntax prevents me from publishing my crate to crates.io (as all dependencies have to be published as well).

@webdesus

**Comment by webdesus** [comment]
@SirWindfield done :smiley: good luck with coding :wink:
