### ISSUE TITLE
copy failed when the filepath has space

### ISSUE THREAD

**Issue by arlicle** [webdesus/fs_extra#26]
Err(Error { kind: NotFound, message: "Path \"/Users/edison/Downloads/123\\ aaaa/归档(5)/panda\" does not exist or you don\'t have access!" })

**Comment by webdesus** [comment]
How are you generate string? i see `\` symbol in you string ... I think you have an error in generating a string. I would recommend using PathBuf. This object correct set path separator

**Comment by webdesus** [comment]
@arlicle you found a problem? Can i close this issue? Or the problem stay?
