### ISSUE TITLE
Skip_Existing vs Overwrite

### ISSUE THREAD

**Issue by smallB007** [webdesus/fs_extra#37]
Hey, what's the difference between SkipExisting and Overwrite? I mean doesn't overwrite selected mean don't skip existing and and not checked means skip existing?
fs_extra::dir::CopyOptions

**Comment by webdesus** [comment]
**SkipExisting** if destenation file name already  exist we skip it, without any errors. Content these files can be different, but we check only name file.
**Overwrite** option always change destenation content file

**Comment by smallB007** [comment]
Yes, but surely they exclude each other? That is, if we have set the flag to Skip, we will not overwrite, and vice versa?
