### ISSUE TITLE
Make a point release

### ISSUE THREAD

**Issue by Aaron1011** [webdesus/fs_extra#47]
I'd appreciate it if you could make a new point release containing https://github.com/webdesus/fs_extra/pull/38. This would help in evaluating the prevalence of macro trailing semicolons in the Rust ecosystem, as I'll be able to bump the `fs_extra` dependency in various places.

Thanks!

**Comment by webdesus** [comment]
Version [1.3.0](https://github.com/webdesus/fs_extra/releases/tag/1.3.0) was publishedslightly_smiling_face
