### ISSUE TITLE
Is this crate still maintained

### ISSUE THREAD

**Issue by a6s5df6a54sd** [webdesus/fs_extra#55]

**Comment by pczarn** [comment]
@a6s5df6a54sd 

I contacted the owner to discuss maintenance.

**Comment by somehowchris** [comment]
@pczarn any response? Would love to use this crate, but an unmaintained crate is, well lets call it "not that nice" 😅

**Comment by webdesus** [comment]
@somehowchris in near future i'm continue support. @pczarn promised to help me :smile:

**Comment by somehowchris** [comment]
@pczarn I‘m happy to help too

**Comment by webdesus** [comment]
@somehowchris glad to hear it. On a next week i make a little plan by  new version :wink:

**Comment by webdesus** [comment]
It took a little longer.. 

Add Contribute.md file, where describe  thouths about development.

And add two RFC document for discuss:
- #57 
- #58 

I'll sort it out a little later with PR-s
