### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jplatte** [webdesus/fs_extra#68]
The latest release produces forwards-compatibility errors, fixed in 5f54a1accfd16167467defe83cc4b879e0bbe528 (Feb 2021) but never released. Could another release be published soon-ish?

**Comment by sylvestre** [comment]
@webdesus could you please help with this ? :)
thanks

**Comment by webdesus** [comment]
Version [1.3.0](https://github.com/webdesus/fs_extra/releases/tag/1.3.0) was published🙂
