### ISSUE TITLE
get child directories

### ISSUE THREAD

**Issue by jaroslaw-weber** [webdesus/fs_extra#7]
Currently DirInfo.directories returns all directories recursively, but I need only to loop through children directories. I thought it was weird that it returns a recursive result by default. Can you add child_directories or change it to get_directories(recursive: bool)?

**Comment by webdesus** [comment]
HI @jaroslaw-weber. I correct understand you speak about it  `fs_extra::dir::get_dir_content` or `fs_extra::dir::get_details_entry`?

**Comment by jaroslaw-weber** [comment]
let x = get_dir_content("./folder_name")?.directories;

**Comment by webdesus** [comment]
Published new version `fs_extra`. For manage read levels use `depth` option of `DirOptions`

**Comment by webdesus** [comment]
Use `fs_extra::dir::get_dir_content2` method for set options. Old method stay for compatibility.

**Comment by realtica** [comment]
Hello, it is possible to exclude the root directory of the results with fs_extra::dir::get_dir_content2  ?
